name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
      - name: Run build 
        run: npm run build --if-present
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-lint-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Installing dependencies
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Run ESLint
        run: npm run lint
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 